# Generated by Django 4.2.6 on 2023-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('JCAT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ldate', models.DateTimeField()),
                ('Sdate', models.DateTimeField()),
                ('Ddate', models.DateTimeField()),
                ('Odate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('JCAT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('OpOrbitOQU', models.CharField(max_length=100)),
                ('inclination', models.FloatField()),
                ('perigee', models.IntegerField()),
                ('apogee', models.IntegerField()),
                ('primary_planet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Satellites',
            fields=[
                ('JCAT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('piece', models.CharField(max_length=50)),
                ('PL_name', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('bus', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('altname', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('JCAT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('motor', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('diameter', models.FloatField()),
                ('mass', models.IntegerField()),
                ('drymass', models.IntegerField()),
                ('tot_mass', models.IntegerField()),
                ('span', models.FloatField()),
                ('shape', models.CharField(max_length=50)),
            ],
        ),
    ]
